pacote explab.plot.plot3d;

classe Superficie3D {

    xvetor = [];
    yvetor = [];
    zmat = [];

    somenteMalha = falso; 

    ponto = novo PontoConfig();
    linha = novo LinhaConfig(); 
    poligono = novo PoligonoConfig();
    
    linha.cor = novo RGB( 0, 0, 0 );

    func setDados( xvet, yvet, zmat ) {
        este.xvetor = xvet;
        este.yvetor = yvet;
        este.zmat = zmat;
    }   

}
