
func f(){}
func pi() {}
func xxx(z,b) {}
func zzz(a,b){retorne pi;};

func x( n ) {
    se n == 1 {
        compare n {
            caso 2 : pare;
            caso 1 :
                func a() { exibaln "XXX"; }
                a();
                retorne 1;            
        }
        retorne 0;
    } senao {
        se ( n == 2 ) {
            exibaln "YYY";
        }
        retorne n * x( n-1 );
    }
}


f();
pi();

xxx(1,2);
z=zzz(1,1);

fat = x( 5 );

exibaln "Fatorial="+fat;
