a = [ 1 2 3; 4 5 6; 7 8 9 ];  // declaração de matriz
b = a(0,2) + a(1,1);          // acessa elemento (0,2) que corresponde ao elemento da 
                              // linha 1 coluna 3. Esse elemento é o número 3
                              // após acessar o elemento de índices (0,2), acessa o de 
                              // índices (1,1), que é o número 5. Realiza a soma e a 
                              // variável "b" recebe o valor 8;							  

c = a(0,1) * a(2,1);          // segue a mesma lógica do valor da expressão atribuido a "b",
                              // "c" passa a valer 2*8, isto é, 16
							  
a(1,:) = [ b b b ];           // acessa a linha 1 (de índice 0) e todas as colunas desta linha, 
                              // são alteradas com os elementos correspondentes aos valores 
                              // do vetor [ b b b ], isto é, [ 8 8 8 ]
							  
a(:,2) = [ c; c; c ];         // acessa a coluna 3 (de índice 2) e todas as linhas desta coluna, 
                              // então substitui os valores desses elementos pelos elementos do 
                              // vetor [ c; c; c ], isto é, [ 16; 16; 16 ]. Perceba que esse vetor 
                              // é de ordem 3x1, e não 1x3. 
                              // Isso porque seus elementos estão separados por ponto e vírgula, não 
                              // por vírgulas ou espaços! E é necessário um vetor vertical para 
                              // ser atribuido a uma coluna							  

exibaln a;	                  // exibe a matriz a, após as alterações da linha 2 (de índice 1) e da 
                              // coluna 3 (de índice 2). O resultado é a matriz:
                              // [ 1 2 16; 8 8 16; 7 8 16 ]	

exibaln a(:);                 // se os elementos de uma matriz bidimensional é acessada assim, seus elementos 
                              // são organizados na vertical. Isto é, se a matriz tem dimensão 3x3, a matriz 
                              // resultante de a(:) é de dimensão 9x1. A matriz impressa é a sequência de todas
                              // as colunas. Isto é: [ 1; 8; 7; 2; 8; 8; 16; 16; 16 ]
                              						  
exibaln a(:,:);               // imprime a matriz inteira: [ 1 2 16; 8 8 16; 7 8 16 ]. a(:,:) é o mesmo que apenas a								  

d = a(:,1);                   // d recebe a matriz linha correspondente a coluna de índice 1. Isto é: [ 2; 8; 8 ]
 
exibaln d;                    // exibe a matriz d