
classe Retangulo {
    
    a = 3;
    b = 4;
    c = 5;

    construtor() {}

    construtor( aa ) {
        este( aa, aa, aa );
    }

    construtor ( aa, bb, cc ) {
        a = aa;
        b = bb;
        c = cc;
    }

    func eh_quadrado() {        
        retorne a == b;
    }

    func eh_retangulo() {
        retorne a != b;
    }

    func area() {
        retorne a*b;
    }

    func area( a, b ) {
        retorne a*b;
    }

}

classe Area {

    raio = 10;

    a = 1;
    b = 2;
    l = 5.5;

    ret1 = novo Retangulo( 5 );
    ret2 = novo Retangulo( 10 );
    ret3 = novo Retangulo( 100, 200, 300 );
    circulo = novo Circulo(); 
    
    z = circulo.a.b.mat( 2 )( 0,: )(1);
    w = verdade & circulo.a.b.eh_maior();    

    func quadrado() {
        retorne l*l;
    }   

    classe Circulo {

        z = 2;        
        a = novo A();        

        classe A {

            b = novo B();

            classe B {
                func area() {
                    retorne pi * (z*raio)^2;
                }
                func mat( a ) {
                    retorne [1 2 3;4 5 6]^a;
                }

                func eh_maior() {
                    exibaln "XX="+este.area();
                    retorne !eh_menor() & este.area() > 10;
                }
            }

        }

        func eh_area() {
            retorne pi * raio^2 > 10;
        }

        func eh_menor() {
            retorne raio < 10;
        }

        func area( raio ) {
            retorne pi * raio^2;
        }
        
    } 

}
