pacote explab.plot.plot2d;

classe Func2D {
    
    x1 = -1;
    x2 = 1;

    y1 = -1;
    y2 = 1;

    limitarY = falso;
    xcompleto = falso;

    legenda = null;

    linha = novo LinhaConfig();

    construtor() {}

    construtor( x1, x2 ) {
        este( x1, x2, null );
    }

    construtor( x1, x2, f ) {
        este.x1 = x1;
        este.x2 = x2;
        este.fun = f;
    }

    este.fun = func( x ) {
        retorne x;
    };  
   
}
